package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type schemaDoc struct {
	Definitions map[string]json.RawMessage `json:"definitions"`
}

type schemaNode struct {
	Ref                  string                     `json:"$ref"`
	Type                 any                        `json:"type"`
	Enum                 []string                   `json:"enum"`
	Properties           map[string]json.RawMessage `json:"properties"`
	Required             []string                   `json:"required"`
	Items                *json.RawMessage           `json:"items"`
	AdditionalProperties *json.RawMessage           `json:"additionalProperties"`
	AnyOf                []json.RawMessage          `json:"anyOf"`
	OneOf                []json.RawMessage          `json:"oneOf"`
	Description          string                     `json:"description"`
	Title                string                     `json:"title"`
}

var manualDefinitions = map[string]struct{}{
	"AgentMessageDeltaNotification":       {},
	"ApprovalsReviewer":                   {},
	"AskForApproval":                      {},
	"ClientInfo":                          {},
	"InitializeCapabilities":              {},
	"InitializeParams":                    {},
	"InitializeResponse":                  {},
	"ItemCompletedNotification":           {},
	"MessagePhase":                        {},
	"Model":                               {},
	"ModelListResponse":                   {},
	"Notification":                        {},
	"Personality":                         {},
	"ReasoningEffort":                     {},
	"ReasoningSummary":                    {},
	"ResourceContent":                     {},
	"RequestId":                           {},
	"RunTurnOptions":                      {},
	"SandboxMode":                         {},
	"SandboxPolicy":                       {},
	"ServerInfo":                          {},
	"ServiceTier":                         {},
	"Thread":                              {},
	"ThreadArchiveResponse":               {},
	"ThreadCompactStartResponse":          {},
	"ThreadForkParams":                    {},
	"ThreadForkResponse":                  {},
	"ThreadInjectItemsResponse":           {},
	"ThreadItem":                          {},
	"ThreadListParams":                    {},
	"ThreadListResponse":                  {},
	"ThreadReadResponse":                  {},
	"ThreadRealtimeStartTransport":        {},
	"ThreadResumeParams":                  {},
	"ThreadResumeResponse":                {},
	"ThreadSetNameResponse":               {},
	"ThreadSortKey":                       {},
	"ThreadSourceKind":                    {},
	"ThreadStartParams":                   {},
	"ThreadStartResponse":                 {},
	"ThreadStatus":                        {},
	"ThreadTokenUsage":                    {},
	"ThreadTokenUsageSample":              {},
	"ThreadTokenUsageUpdatedNotification": {},
	"ThreadUnarchiveResponse":             {},
	"Turn":                                {},
	"TurnCompletedNotification":           {},
	"TurnError":                           {},
	"TurnInterruptResponse":               {},
	"TurnStartParams":                     {},
	"TurnStartResponse":                   {},
	"TurnStatus":                          {},
	"TurnSteerResponse":                   {},
	"UserInput":                           {},
}

func main() {
	var (
		schemaPath string
		outPath    string
	)

	flag.StringVar(
		&schemaPath,
		"schema",
		filepath.Join("..", "..", "codex-rs", "app-server-protocol", "schema", "json", "codex_app_server_protocol.v2.schemas.json"),
		"path to app-server v2 schema bundle",
	)
	flag.StringVar(
		&outPath,
		"out",
		filepath.Join("protocol", "generated.go"),
		"generated Go output path",
	)
	flag.Parse()

	if err := run(schemaPath, outPath); err != nil {
		fmt.Fprintf(os.Stderr, "generate: %v\n", err)
		os.Exit(1)
	}
}

func run(schemaPath, outPath string) error {
	data, err := os.ReadFile(schemaPath)
	if err != nil {
		return err
	}

	var doc schemaDoc
	if err := json.Unmarshal(data, &doc); err != nil {
		return err
	}

	names := make([]string, 0, len(doc.Definitions))
	for name := range doc.Definitions {
		if _, skip := manualDefinitions[name]; skip {
			continue
		}
		names = append(names, name)
	}
	sort.Strings(names)

	var buf bytes.Buffer
	buf.WriteString("// Code generated by go run ./cmd/generate. DO NOT EDIT.\n\n")
	buf.WriteString("package protocol\n\n")
	buf.WriteString("import \"encoding/json\"\n\n")

	for _, name := range names {
		var node schemaNode
		if err := json.Unmarshal(doc.Definitions[name], &node); err != nil {
			return fmt.Errorf("decode %s: %w", name, err)
		}

		rendered, err := renderDefinition(name, node)
		if err != nil {
			return fmt.Errorf("render %s: %w", name, err)
		}
		buf.WriteString(rendered)
		buf.WriteString("\n")
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("gofmt generated output: %w", err)
	}

	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(outPath, formatted, 0o644)
}

func renderDefinition(name string, node schemaNode) (string, error) {
	if len(node.Enum) > 0 {
		return renderEnum(name, node.Enum), nil
	}
	if node.Ref != "" {
		return fmt.Sprintf("type %s = %s\n", name, refName(node.Ref)), nil
	}

	switch normalizedType(node.Type) {
	case "object":
		if len(node.Properties) == 0 && node.AdditionalProperties != nil {
			elemType, _ := renderFieldType(*node.AdditionalProperties)
			if elemType == "" {
				elemType = "any"
			}
			return fmt.Sprintf("type %s map[string]%s\n", name, elemType), nil
		}
		if len(node.Properties) == 0 {
			return fmt.Sprintf("type %s = json.RawMessage\n", name), nil
		}
		return renderStruct(name, node)
	case "array":
		if node.Items == nil {
			return fmt.Sprintf("type %s = []json.RawMessage\n", name), nil
		}
		elemType, _ := renderFieldType(*node.Items)
		if elemType == "" {
			elemType = "json.RawMessage"
		}
		return fmt.Sprintf("type %s = []%s\n", name, elemType), nil
	case "string":
		return fmt.Sprintf("type %s = string\n", name), nil
	case "integer":
		return fmt.Sprintf("type %s = int64\n", name), nil
	case "number":
		return fmt.Sprintf("type %s = float64\n", name), nil
	case "boolean":
		return fmt.Sprintf("type %s = bool\n", name), nil
	}

	if nullableSubschema(node.AnyOf) != nil || nullableSubschema(node.OneOf) != nil {
		return fmt.Sprintf("type %s = json.RawMessage\n", name), nil
	}

	return fmt.Sprintf("type %s = json.RawMessage\n", name), nil
}

func renderStruct(name string, node schemaNode) (string, error) {
	required := make(map[string]struct{}, len(node.Required))
	for _, field := range node.Required {
		required[field] = struct{}{}
	}

	fieldNames := make([]string, 0, len(node.Properties))
	for fieldName := range node.Properties {
		fieldNames = append(fieldNames, fieldName)
	}
	sort.Strings(fieldNames)

	var buf strings.Builder
	buf.WriteString(fmt.Sprintf("type %s struct {\n", name))
	for _, fieldName := range fieldNames {
		goType, err := renderFieldType(node.Properties[fieldName])
		if err != nil {
			return "", err
		}
		if goType == "" {
			goType = "json.RawMessage"
		}
		if _, isRequired := required[fieldName]; !isRequired {
			goType = optionalize(goType)
		}
		tag := fieldName
		if _, isRequired := required[fieldName]; !isRequired {
			tag += ",omitempty"
		}
		buf.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n", toExported(fieldName), goType, tag))
	}
	buf.WriteString("}\n")
	return buf.String(), nil
}

func renderEnum(name string, values []string) string {
	var buf strings.Builder
	buf.WriteString(fmt.Sprintf("type %s string\n\n", name))
	buf.WriteString("const (\n")
	for _, value := range values {
		buf.WriteString(fmt.Sprintf("\t%s%s %s = %q\n", name, toExported(value), name, value))
	}
	buf.WriteString(")\n")
	return buf.String()
}

func renderFieldType(raw json.RawMessage) (string, error) {
	trimmed := strings.TrimSpace(string(raw))
	if trimmed == "true" {
		return "map[string]any", nil
	}
	if trimmed == "false" {
		return "json.RawMessage", nil
	}

	var node schemaNode
	if err := json.Unmarshal(raw, &node); err != nil {
		return "", err
	}
	if node.Ref != "" {
		return refName(node.Ref), nil
	}
	if sub := nullableSubschema(node.AnyOf); sub != nil {
		typ, err := renderFieldType(*sub)
		if err != nil {
			return "", err
		}
		return optionalize(typ), nil
	}
	if sub := nullableSubschema(node.OneOf); sub != nil {
		typ, err := renderFieldType(*sub)
		if err != nil {
			return "", err
		}
		return optionalize(typ), nil
	}
	if len(node.Enum) > 0 {
		return "string", nil
	}

	switch normalizedType(node.Type) {
	case "string":
		return "string", nil
	case "integer":
		return "int64", nil
	case "number":
		return "float64", nil
	case "boolean":
		return "bool", nil
	case "array":
		if node.Items == nil {
			return "[]json.RawMessage", nil
		}
		elemType, err := renderFieldType(*node.Items)
		if err != nil {
			return "", err
		}
		if elemType == "" {
			elemType = "json.RawMessage"
		}
		return "[]" + trimPointer(elemType), nil
	case "object":
		if len(node.Properties) == 0 {
			if node.AdditionalProperties != nil {
				elemType, err := renderFieldType(*node.AdditionalProperties)
				if err != nil {
					return "", err
				}
				if elemType == "" {
					elemType = "any"
				}
				return "map[string]" + trimPointer(elemType), nil
			}
			return "map[string]any", nil
		}
		return "json.RawMessage", nil
	}

	return "json.RawMessage", nil
}

func nullableSubschema(nodes []json.RawMessage) *json.RawMessage {
	if len(nodes) != 2 {
		return nil
	}
	var candidate *json.RawMessage
	for i := range nodes {
		trimmed := strings.TrimSpace(string(nodes[i]))
		if trimmed == "null" {
			continue
		}
		var node schemaNode
		if err := json.Unmarshal(nodes[i], &node); err != nil {
			return nil
		}
		if isNullType(node.Type) {
			continue
		}
		if candidate != nil {
			return nil
		}
		candidate = &nodes[i]
	}
	return candidate
}

func normalizedType(raw any) string {
	switch value := raw.(type) {
	case string:
		return value
	case []any:
		for _, item := range value {
			if itemStr, ok := item.(string); ok && itemStr != "null" {
				return itemStr
			}
		}
	}
	return ""
}

func isNullType(raw any) bool {
	switch value := raw.(type) {
	case string:
		return value == "null"
	case []any:
		for _, item := range value {
			if itemStr, ok := item.(string); ok && itemStr == "null" {
				return true
			}
		}
	}
	return false
}

func refName(ref string) string {
	ref = strings.TrimPrefix(ref, "#/definitions/")
	ref = strings.TrimPrefix(ref, "v2/")
	parts := strings.Split(ref, "/")
	return parts[len(parts)-1]
}

func toExported(value string) string {
	parts := strings.FieldsFunc(value, func(r rune) bool {
		return !(r >= '0' && r <= '9' || r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z')
	})
	if len(parts) == 0 {
		return "Value"
	}
	var out strings.Builder
	for _, part := range parts {
		lower := strings.ToLower(part)
		switch lower {
		case "id":
			out.WriteString("ID")
		case "url":
			out.WriteString("URL")
		case "cwd":
			out.WriteString("Cwd")
		case "api":
			out.WriteString("API")
		case "os":
			out.WriteString("OS")
		default:
			out.WriteString(strings.ToUpper(part[:1]))
			out.WriteString(part[1:])
		}
	}
	return out.String()
}

func optionalize(goType string) string {
	if goType == "" {
		return "json.RawMessage"
	}
	if strings.HasPrefix(goType, "*") || strings.HasPrefix(goType, "[]") || strings.HasPrefix(goType, "map[") || goType == "json.RawMessage" || goType == "any" {
		return goType
	}
	return "*" + goType
}

func trimPointer(goType string) string {
	return strings.TrimPrefix(goType, "*")
}
