// Code generated by go run ./cmd/generate. DO NOT EDIT.

package protocol

import "encoding/json"

type AbsolutePathBuf = string

type Account = json.RawMessage

type AccountLoginCompletedNotification struct {
	Error   *string `json:"error,omitempty"`
	LoginId *string `json:"loginId,omitempty"`
	Success bool    `json:"success"`
}

type AccountRateLimitsUpdatedNotification struct {
	RateLimits RateLimitSnapshot `json:"rateLimits"`
}

type AccountUpdatedNotification struct {
	AuthMode *AuthMode `json:"authMode,omitempty"`
	PlanType *PlanType `json:"planType,omitempty"`
}

type ActivePermissionProfile struct {
	Extends       *string                               `json:"extends,omitempty"`
	ID            string                                `json:"id"`
	Modifications []ActivePermissionProfileModification `json:"modifications,omitempty"`
}

type ActivePermissionProfileModification = json.RawMessage

type AddCreditsNudgeCreditType string

const (
	AddCreditsNudgeCreditTypeCredits    AddCreditsNudgeCreditType = "credits"
	AddCreditsNudgeCreditTypeUsageLimit AddCreditsNudgeCreditType = "usage_limit"
)

type AddCreditsNudgeEmailStatus string

const (
	AddCreditsNudgeEmailStatusSent           AddCreditsNudgeEmailStatus = "sent"
	AddCreditsNudgeEmailStatusCooldownActive AddCreditsNudgeEmailStatus = "cooldown_active"
)

type AdditionalFileSystemPermissions struct {
	Entries          []FileSystemSandboxEntry `json:"entries,omitempty"`
	GlobScanMaxDepth *int64                   `json:"globScanMaxDepth,omitempty"`
	Read             []AbsolutePathBuf        `json:"read,omitempty"`
	Write            []AbsolutePathBuf        `json:"write,omitempty"`
}

type AdditionalNetworkPermissions struct {
	Enabled *bool `json:"enabled,omitempty"`
}

type AgentPath = string

type AnalyticsConfig struct {
	Enabled *bool `json:"enabled,omitempty"`
}

type AppBranding struct {
	Category          *string `json:"category,omitempty"`
	Developer         *string `json:"developer,omitempty"`
	IsDiscoverableApp bool    `json:"isDiscoverableApp"`
	PrivacyPolicy     *string `json:"privacyPolicy,omitempty"`
	TermsOfService    *string `json:"termsOfService,omitempty"`
	Website           *string `json:"website,omitempty"`
}

type AppConfig struct {
	DefaultToolsApprovalMode *AppToolApproval `json:"default_tools_approval_mode,omitempty"`
	DefaultToolsEnabled      *bool            `json:"default_tools_enabled,omitempty"`
	DestructiveEnabled       *bool            `json:"destructive_enabled,omitempty"`
	Enabled                  *bool            `json:"enabled,omitempty"`
	OpenWorldEnabled         *bool            `json:"open_world_enabled,omitempty"`
	Tools                    *AppToolsConfig  `json:"tools,omitempty"`
}

type AppInfo struct {
	AppMetadata         *AppMetadata      `json:"appMetadata,omitempty"`
	Branding            *AppBranding      `json:"branding,omitempty"`
	Description         *string           `json:"description,omitempty"`
	DistributionChannel *string           `json:"distributionChannel,omitempty"`
	ID                  string            `json:"id"`
	InstallUrl          *string           `json:"installUrl,omitempty"`
	IsAccessible        *bool             `json:"isAccessible,omitempty"`
	IsEnabled           *bool             `json:"isEnabled,omitempty"`
	Labels              map[string]string `json:"labels,omitempty"`
	LogoUrl             *string           `json:"logoUrl,omitempty"`
	LogoUrlDark         *string           `json:"logoUrlDark,omitempty"`
	Name                string            `json:"name"`
	PluginDisplayNames  []string          `json:"pluginDisplayNames,omitempty"`
}

type AppListUpdatedNotification struct {
	Data []AppInfo `json:"data"`
}

type AppMetadata struct {
	Categories                 []string        `json:"categories,omitempty"`
	Developer                  *string         `json:"developer,omitempty"`
	FirstPartyRequiresInstall  *bool           `json:"firstPartyRequiresInstall,omitempty"`
	FirstPartyType             *string         `json:"firstPartyType,omitempty"`
	Review                     *AppReview      `json:"review,omitempty"`
	Screenshots                []AppScreenshot `json:"screenshots,omitempty"`
	SeoDescription             *string         `json:"seoDescription,omitempty"`
	ShowInComposerWhenUnlinked *bool           `json:"showInComposerWhenUnlinked,omitempty"`
	SubCategories              []string        `json:"subCategories,omitempty"`
	Version                    *string         `json:"version,omitempty"`
	VersionId                  *string         `json:"versionId,omitempty"`
	VersionNotes               *string         `json:"versionNotes,omitempty"`
}

type AppReview struct {
	Status string `json:"status"`
}

type AppScreenshot struct {
	FileId     *string `json:"fileId,omitempty"`
	URL        *string `json:"url,omitempty"`
	UserPrompt string  `json:"userPrompt"`
}

type AppSummary struct {
	Description *string `json:"description,omitempty"`
	ID          string  `json:"id"`
	InstallUrl  *string `json:"installUrl,omitempty"`
	Name        string  `json:"name"`
	NeedsAuth   bool    `json:"needsAuth"`
}

type AppToolApproval string

const (
	AppToolApprovalAuto    AppToolApproval = "auto"
	AppToolApprovalPrompt  AppToolApproval = "prompt"
	AppToolApprovalApprove AppToolApproval = "approve"
)

type AppToolConfig struct {
	ApprovalMode *AppToolApproval `json:"approval_mode,omitempty"`
	Enabled      *bool            `json:"enabled,omitempty"`
}

type AppToolsConfig = json.RawMessage

type AppsConfig struct {
	Default *AppsDefaultConfig `json:"_default,omitempty"`
}

type AppsDefaultConfig struct {
	DestructiveEnabled *bool `json:"destructive_enabled,omitempty"`
	Enabled            *bool `json:"enabled,omitempty"`
	OpenWorldEnabled   *bool `json:"open_world_enabled,omitempty"`
}

type AppsListParams struct {
	Cursor       *string `json:"cursor,omitempty"`
	ForceRefetch *bool   `json:"forceRefetch,omitempty"`
	Limit        *int64  `json:"limit,omitempty"`
	ThreadId     *string `json:"threadId,omitempty"`
}

type AppsListResponse struct {
	Data       []AppInfo `json:"data"`
	NextCursor *string   `json:"nextCursor,omitempty"`
}

type AuthMode = json.RawMessage

type AutoReviewDecisionSource string

const (
	AutoReviewDecisionSourceAgent AutoReviewDecisionSource = "agent"
)

type ByteRange struct {
	End   int64 `json:"end"`
	Start int64 `json:"start"`
}

type CancelLoginAccountParams struct {
	LoginId string `json:"loginId"`
}

type CancelLoginAccountResponse struct {
	Status CancelLoginAccountStatus `json:"status"`
}

type CancelLoginAccountStatus string

const (
	CancelLoginAccountStatusCanceled CancelLoginAccountStatus = "canceled"
	CancelLoginAccountStatusNotFound CancelLoginAccountStatus = "notFound"
)

type ClientRequest = json.RawMessage

type CodexErrorInfo = json.RawMessage

type CollabAgentState struct {
	Message *string           `json:"message,omitempty"`
	Status  CollabAgentStatus `json:"status"`
}

type CollabAgentStatus string

const (
	CollabAgentStatusPendingInit CollabAgentStatus = "pendingInit"
	CollabAgentStatusRunning     CollabAgentStatus = "running"
	CollabAgentStatusInterrupted CollabAgentStatus = "interrupted"
	CollabAgentStatusCompleted   CollabAgentStatus = "completed"
	CollabAgentStatusErrored     CollabAgentStatus = "errored"
	CollabAgentStatusShutdown    CollabAgentStatus = "shutdown"
	CollabAgentStatusNotFound    CollabAgentStatus = "notFound"
)

type CollabAgentTool string

const (
	CollabAgentToolSpawnAgent  CollabAgentTool = "spawnAgent"
	CollabAgentToolSendInput   CollabAgentTool = "sendInput"
	CollabAgentToolResumeAgent CollabAgentTool = "resumeAgent"
	CollabAgentToolWait        CollabAgentTool = "wait"
	CollabAgentToolCloseAgent  CollabAgentTool = "closeAgent"
)

type CollabAgentToolCallStatus string

const (
	CollabAgentToolCallStatusInProgress CollabAgentToolCallStatus = "inProgress"
	CollabAgentToolCallStatusCompleted  CollabAgentToolCallStatus = "completed"
	CollabAgentToolCallStatusFailed     CollabAgentToolCallStatus = "failed"
)

type CollaborationMode struct {
	Mode     ModeKind `json:"mode"`
	Settings Settings `json:"settings"`
}

type CollaborationModeMask struct {
	Mode            *ModeKind        `json:"mode,omitempty"`
	Model           *string          `json:"model,omitempty"`
	Name            string           `json:"name"`
	ReasoningEffort *ReasoningEffort `json:"reasoning_effort,omitempty"`
}

type CommandAction = json.RawMessage

type CommandExecOutputDeltaNotification struct {
	CapReached  bool            `json:"capReached"`
	DeltaBase64 string          `json:"deltaBase64"`
	ProcessId   string          `json:"processId"`
	Stream      json.RawMessage `json:"stream"`
}

type CommandExecOutputStream = json.RawMessage

type CommandExecParams struct {
	Command            []string                 `json:"command"`
	Cwd                *string                  `json:"cwd,omitempty"`
	DisableOutputCap   *bool                    `json:"disableOutputCap,omitempty"`
	DisableTimeout     *bool                    `json:"disableTimeout,omitempty"`
	Env                map[string]string        `json:"env,omitempty"`
	OutputBytesCap     *int64                   `json:"outputBytesCap,omitempty"`
	ProcessId          *string                  `json:"processId,omitempty"`
	SandboxPolicy      *SandboxPolicy           `json:"sandboxPolicy,omitempty"`
	Size               *CommandExecTerminalSize `json:"size,omitempty"`
	StreamStdin        *bool                    `json:"streamStdin,omitempty"`
	StreamStdoutStderr *bool                    `json:"streamStdoutStderr,omitempty"`
	TimeoutMs          *int64                   `json:"timeoutMs,omitempty"`
	Tty                *bool                    `json:"tty,omitempty"`
}

type CommandExecResizeParams struct {
	ProcessId string          `json:"processId"`
	Size      json.RawMessage `json:"size"`
}

type CommandExecResizeResponse = json.RawMessage

type CommandExecResponse struct {
	ExitCode int64  `json:"exitCode"`
	Stderr   string `json:"stderr"`
	Stdout   string `json:"stdout"`
}

type CommandExecTerminalSize struct {
	Cols int64 `json:"cols"`
	Rows int64 `json:"rows"`
}

type CommandExecTerminateParams struct {
	ProcessId string `json:"processId"`
}

type CommandExecTerminateResponse = json.RawMessage

type CommandExecWriteParams struct {
	CloseStdin  *bool   `json:"closeStdin,omitempty"`
	DeltaBase64 *string `json:"deltaBase64,omitempty"`
	ProcessId   string  `json:"processId"`
}

type CommandExecWriteResponse = json.RawMessage

type CommandExecutionOutputDeltaNotification struct {
	Delta    string `json:"delta"`
	ItemId   string `json:"itemId"`
	ThreadId string `json:"threadId"`
	TurnId   string `json:"turnId"`
}

type CommandExecutionSource string

const (
	CommandExecutionSourceAgent                  CommandExecutionSource = "agent"
	CommandExecutionSourceUserShell              CommandExecutionSource = "userShell"
	CommandExecutionSourceUnifiedExecStartup     CommandExecutionSource = "unifiedExecStartup"
	CommandExecutionSourceUnifiedExecInteraction CommandExecutionSource = "unifiedExecInteraction"
)

type CommandExecutionStatus string

const (
	CommandExecutionStatusInProgress CommandExecutionStatus = "inProgress"
	CommandExecutionStatusCompleted  CommandExecutionStatus = "completed"
	CommandExecutionStatusFailed     CommandExecutionStatus = "failed"
	CommandExecutionStatusDeclined   CommandExecutionStatus = "declined"
)

type CommandMigration struct {
	Name string `json:"name"`
}

type Config struct {
	Analytics                  *AnalyticsConfig       `json:"analytics,omitempty"`
	ApprovalPolicy             *AskForApproval        `json:"approval_policy,omitempty"`
	ApprovalsReviewer          *ApprovalsReviewer     `json:"approvals_reviewer,omitempty"`
	CompactPrompt              *string                `json:"compact_prompt,omitempty"`
	DeveloperInstructions      *string                `json:"developer_instructions,omitempty"`
	ForcedChatgptWorkspaceID   *string                `json:"forced_chatgpt_workspace_id,omitempty"`
	ForcedLoginMethod          *ForcedLoginMethod     `json:"forced_login_method,omitempty"`
	Instructions               *string                `json:"instructions,omitempty"`
	Model                      *string                `json:"model,omitempty"`
	ModelAutoCompactTokenLimit *int64                 `json:"model_auto_compact_token_limit,omitempty"`
	ModelContextWindow         *int64                 `json:"model_context_window,omitempty"`
	ModelProvider              *string                `json:"model_provider,omitempty"`
	ModelReasoningEffort       *ReasoningEffort       `json:"model_reasoning_effort,omitempty"`
	ModelReasoningSummary      *ReasoningSummary      `json:"model_reasoning_summary,omitempty"`
	ModelVerbosity             *Verbosity             `json:"model_verbosity,omitempty"`
	Profile                    *string                `json:"profile,omitempty"`
	Profiles                   map[string]ProfileV2   `json:"profiles,omitempty"`
	ReviewModel                *string                `json:"review_model,omitempty"`
	SandboxMode                *SandboxMode           `json:"sandbox_mode,omitempty"`
	SandboxWorkspaceWrite      *SandboxWorkspaceWrite `json:"sandbox_workspace_write,omitempty"`
	ServiceTier                *string                `json:"service_tier,omitempty"`
	Tools                      *ToolsV2               `json:"tools,omitempty"`
	WebSearch                  *WebSearchMode         `json:"web_search,omitempty"`
}

type ConfigBatchWriteParams struct {
	Edits            []ConfigEdit `json:"edits"`
	ExpectedVersion  *string      `json:"expectedVersion,omitempty"`
	FilePath         *string      `json:"filePath,omitempty"`
	ReloadUserConfig *bool        `json:"reloadUserConfig,omitempty"`
}

type ConfigEdit struct {
	KeyPath       string         `json:"keyPath"`
	MergeStrategy MergeStrategy  `json:"mergeStrategy"`
	Value         map[string]any `json:"value"`
}

type ConfigLayer struct {
	Config         map[string]any    `json:"config"`
	DisabledReason *string           `json:"disabledReason,omitempty"`
	Name           ConfigLayerSource `json:"name"`
	Version        string            `json:"version"`
}

type ConfigLayerMetadata struct {
	Name    ConfigLayerSource `json:"name"`
	Version string            `json:"version"`
}

type ConfigLayerSource = json.RawMessage

type ConfigReadParams struct {
	Cwd           *string `json:"cwd,omitempty"`
	IncludeLayers *bool   `json:"includeLayers,omitempty"`
}

type ConfigReadResponse struct {
	Config  Config                         `json:"config"`
	Layers  []ConfigLayer                  `json:"layers,omitempty"`
	Origins map[string]ConfigLayerMetadata `json:"origins"`
}

type ConfigRequirements struct {
	AllowedApprovalPolicies []AskForApproval      `json:"allowedApprovalPolicies,omitempty"`
	AllowedSandboxModes     []SandboxMode         `json:"allowedSandboxModes,omitempty"`
	AllowedWebSearchModes   []WebSearchMode       `json:"allowedWebSearchModes,omitempty"`
	EnforceResidency        *ResidencyRequirement `json:"enforceResidency,omitempty"`
	FeatureRequirements     map[string]bool       `json:"featureRequirements,omitempty"`
}

type ConfigRequirementsReadResponse struct {
	Requirements *ConfigRequirements `json:"requirements,omitempty"`
}

type ConfigValueWriteParams struct {
	ExpectedVersion *string        `json:"expectedVersion,omitempty"`
	FilePath        *string        `json:"filePath,omitempty"`
	KeyPath         string         `json:"keyPath"`
	MergeStrategy   MergeStrategy  `json:"mergeStrategy"`
	Value           map[string]any `json:"value"`
}

type ConfigWarningNotification struct {
	Details *string    `json:"details,omitempty"`
	Path    *string    `json:"path,omitempty"`
	Range   *TextRange `json:"range,omitempty"`
	Summary string     `json:"summary"`
}

type ConfigWriteResponse struct {
	FilePath           json.RawMessage     `json:"filePath"`
	OverriddenMetadata *OverriddenMetadata `json:"overriddenMetadata,omitempty"`
	Status             WriteStatus         `json:"status"`
	Version            string              `json:"version"`
}

type ConfiguredHookHandler = json.RawMessage

type ConfiguredHookMatcherGroup struct {
	Hooks   []ConfiguredHookHandler `json:"hooks"`
	Matcher *string                 `json:"matcher,omitempty"`
}

type ContentItem = json.RawMessage

type ContextCompactedNotification struct {
	ThreadId string `json:"threadId"`
	TurnId   string `json:"turnId"`
}

type CreditsSnapshot struct {
	Balance    *string `json:"balance,omitempty"`
	HasCredits bool    `json:"hasCredits"`
	Unlimited  bool    `json:"unlimited"`
}

type DeprecationNoticeNotification struct {
	Details *string `json:"details,omitempty"`
	Summary string  `json:"summary"`
}

type DynamicToolCallOutputContentItem = json.RawMessage

type DynamicToolCallStatus string

const (
	DynamicToolCallStatusInProgress DynamicToolCallStatus = "inProgress"
	DynamicToolCallStatusCompleted  DynamicToolCallStatus = "completed"
	DynamicToolCallStatusFailed     DynamicToolCallStatus = "failed"
)

type DynamicToolSpec struct {
	DeferLoading *bool          `json:"deferLoading,omitempty"`
	Description  string         `json:"description"`
	InputSchema  map[string]any `json:"inputSchema"`
	Name         string         `json:"name"`
	Namespace    *string        `json:"namespace,omitempty"`
}

type ErrorNotification struct {
	Error     TurnError `json:"error"`
	ThreadId  string    `json:"threadId"`
	TurnId    string    `json:"turnId"`
	WillRetry bool      `json:"willRetry"`
}

type ExperimentalFeature struct {
	Announcement   *string         `json:"announcement,omitempty"`
	DefaultEnabled bool            `json:"defaultEnabled"`
	Description    *string         `json:"description,omitempty"`
	DisplayName    *string         `json:"displayName,omitempty"`
	Enabled        bool            `json:"enabled"`
	Name           string          `json:"name"`
	Stage          json.RawMessage `json:"stage"`
}

type ExperimentalFeatureEnablementSetParams struct {
	Enablement map[string]bool `json:"enablement"`
}

type ExperimentalFeatureEnablementSetResponse struct {
	Enablement map[string]bool `json:"enablement"`
}

type ExperimentalFeatureListParams struct {
	Cursor *string `json:"cursor,omitempty"`
	Limit  *int64  `json:"limit,omitempty"`
}

type ExperimentalFeatureListResponse struct {
	Data       []ExperimentalFeature `json:"data"`
	NextCursor *string               `json:"nextCursor,omitempty"`
}

type ExperimentalFeatureStage = json.RawMessage

type ExternalAgentConfigDetectParams struct {
	Cwds        []string `json:"cwds,omitempty"`
	IncludeHome *bool    `json:"includeHome,omitempty"`
}

type ExternalAgentConfigDetectResponse struct {
	Items []ExternalAgentConfigMigrationItem `json:"items"`
}

type ExternalAgentConfigImportCompletedNotification = json.RawMessage

type ExternalAgentConfigImportParams struct {
	MigrationItems []ExternalAgentConfigMigrationItem `json:"migrationItems"`
}

type ExternalAgentConfigImportResponse = json.RawMessage

type ExternalAgentConfigMigrationItem struct {
	Cwd         *string                              `json:"cwd,omitempty"`
	Description string                               `json:"description"`
	Details     *MigrationDetails                    `json:"details,omitempty"`
	ItemType    ExternalAgentConfigMigrationItemType `json:"itemType"`
}

type ExternalAgentConfigMigrationItemType string

const (
	ExternalAgentConfigMigrationItemTypeAGENTSMD        ExternalAgentConfigMigrationItemType = "AGENTS_MD"
	ExternalAgentConfigMigrationItemTypeCONFIG          ExternalAgentConfigMigrationItemType = "CONFIG"
	ExternalAgentConfigMigrationItemTypeSKILLS          ExternalAgentConfigMigrationItemType = "SKILLS"
	ExternalAgentConfigMigrationItemTypePLUGINS         ExternalAgentConfigMigrationItemType = "PLUGINS"
	ExternalAgentConfigMigrationItemTypeMCPSERVERCONFIG ExternalAgentConfigMigrationItemType = "MCP_SERVER_CONFIG"
	ExternalAgentConfigMigrationItemTypeSUBAGENTS       ExternalAgentConfigMigrationItemType = "SUBAGENTS"
	ExternalAgentConfigMigrationItemTypeHOOKS           ExternalAgentConfigMigrationItemType = "HOOKS"
	ExternalAgentConfigMigrationItemTypeCOMMANDS        ExternalAgentConfigMigrationItemType = "COMMANDS"
	ExternalAgentConfigMigrationItemTypeSESSIONS        ExternalAgentConfigMigrationItemType = "SESSIONS"
)

type FeedbackUploadParams struct {
	Classification string            `json:"classification"`
	ExtraLogFiles  []string          `json:"extraLogFiles,omitempty"`
	IncludeLogs    bool              `json:"includeLogs"`
	Reason         *string           `json:"reason,omitempty"`
	Tags           map[string]string `json:"tags,omitempty"`
	ThreadId       *string           `json:"threadId,omitempty"`
}

type FeedbackUploadResponse struct {
	ThreadId string `json:"threadId"`
}

type FileChangeOutputDeltaNotification struct {
	Delta    string `json:"delta"`
	ItemId   string `json:"itemId"`
	ThreadId string `json:"threadId"`
	TurnId   string `json:"turnId"`
}

type FileChangePatchUpdatedNotification struct {
	Changes  []FileUpdateChange `json:"changes"`
	ItemId   string             `json:"itemId"`
	ThreadId string             `json:"threadId"`
	TurnId   string             `json:"turnId"`
}

type FileSystemAccessMode string

const (
	FileSystemAccessModeRead  FileSystemAccessMode = "read"
	FileSystemAccessModeWrite FileSystemAccessMode = "write"
	FileSystemAccessModeNone  FileSystemAccessMode = "none"
)

type FileSystemPath = json.RawMessage

type FileSystemSandboxEntry struct {
	Access FileSystemAccessMode `json:"access"`
	Path   FileSystemPath       `json:"path"`
}

type FileSystemSpecialPath = json.RawMessage

type FileUpdateChange struct {
	Diff string          `json:"diff"`
	Kind PatchChangeKind `json:"kind"`
	Path string          `json:"path"`
}

type ForcedLoginMethod string

const (
	ForcedLoginMethodChatgpt ForcedLoginMethod = "chatgpt"
	ForcedLoginMethodAPI     ForcedLoginMethod = "api"
)

type FsChangedNotification struct {
	ChangedPaths []AbsolutePathBuf `json:"changedPaths"`
	WatchId      string            `json:"watchId"`
}

type FsCopyParams struct {
	DestinationPath json.RawMessage `json:"destinationPath"`
	Recursive       *bool           `json:"recursive,omitempty"`
	SourcePath      json.RawMessage `json:"sourcePath"`
}

type FsCopyResponse = json.RawMessage

type FsCreateDirectoryParams struct {
	Path      json.RawMessage `json:"path"`
	Recursive *bool           `json:"recursive,omitempty"`
}

type FsCreateDirectoryResponse = json.RawMessage

type FsGetMetadataParams struct {
	Path json.RawMessage `json:"path"`
}

type FsGetMetadataResponse struct {
	CreatedAtMs  int64 `json:"createdAtMs"`
	IsDirectory  bool  `json:"isDirectory"`
	IsFile       bool  `json:"isFile"`
	IsSymlink    bool  `json:"isSymlink"`
	ModifiedAtMs int64 `json:"modifiedAtMs"`
}

type FsReadDirectoryEntry struct {
	FileName    string `json:"fileName"`
	IsDirectory bool   `json:"isDirectory"`
	IsFile      bool   `json:"isFile"`
}

type FsReadDirectoryParams struct {
	Path json.RawMessage `json:"path"`
}

type FsReadDirectoryResponse struct {
	Entries []FsReadDirectoryEntry `json:"entries"`
}

type FsReadFileParams struct {
	Path json.RawMessage `json:"path"`
}

type FsReadFileResponse struct {
	DataBase64 string `json:"dataBase64"`
}

type FsRemoveParams struct {
	Force     *bool           `json:"force,omitempty"`
	Path      json.RawMessage `json:"path"`
	Recursive *bool           `json:"recursive,omitempty"`
}

type FsRemoveResponse = json.RawMessage

type FsUnwatchParams struct {
	WatchId string `json:"watchId"`
}

type FsUnwatchResponse = json.RawMessage

type FsWatchParams struct {
	Path    json.RawMessage `json:"path"`
	WatchId string          `json:"watchId"`
}

type FsWatchResponse struct {
	Path json.RawMessage `json:"path"`
}

type FsWriteFileParams struct {
	DataBase64 string          `json:"dataBase64"`
	Path       json.RawMessage `json:"path"`
}

type FsWriteFileResponse = json.RawMessage

type FunctionCallOutputBody = json.RawMessage

type FunctionCallOutputContentItem = json.RawMessage

type FuzzyFileSearchMatchType string

const (
	FuzzyFileSearchMatchTypeFile      FuzzyFileSearchMatchType = "file"
	FuzzyFileSearchMatchTypeDirectory FuzzyFileSearchMatchType = "directory"
)

type FuzzyFileSearchParams struct {
	CancellationToken *string  `json:"cancellationToken,omitempty"`
	Query             string   `json:"query"`
	Roots             []string `json:"roots"`
}

type FuzzyFileSearchResult struct {
	FileName  string                   `json:"file_name"`
	Indices   []int64                  `json:"indices,omitempty"`
	MatchType FuzzyFileSearchMatchType `json:"match_type"`
	Path      string                   `json:"path"`
	Root      string                   `json:"root"`
	Score     int64                    `json:"score"`
}

type FuzzyFileSearchSessionCompletedNotification struct {
	SessionId string `json:"sessionId"`
}

type FuzzyFileSearchSessionUpdatedNotification struct {
	Files     []FuzzyFileSearchResult `json:"files"`
	Query     string                  `json:"query"`
	SessionId string                  `json:"sessionId"`
}

type GetAccountParams struct {
	RefreshToken *bool `json:"refreshToken,omitempty"`
}

type GetAccountRateLimitsResponse struct {
	RateLimits          json.RawMessage              `json:"rateLimits"`
	RateLimitsByLimitId map[string]RateLimitSnapshot `json:"rateLimitsByLimitId,omitempty"`
}

type GetAccountResponse struct {
	Account            *Account `json:"account,omitempty"`
	RequiresOpenaiAuth bool     `json:"requiresOpenaiAuth"`
}

type GitInfo struct {
	Branch    *string `json:"branch,omitempty"`
	OriginUrl *string `json:"originUrl,omitempty"`
	Sha       *string `json:"sha,omitempty"`
}

type GuardianApprovalReview struct {
	Rationale         *string                      `json:"rationale,omitempty"`
	RiskLevel         *GuardianRiskLevel           `json:"riskLevel,omitempty"`
	Status            GuardianApprovalReviewStatus `json:"status"`
	UserAuthorization *GuardianUserAuthorization   `json:"userAuthorization,omitempty"`
}

type GuardianApprovalReviewAction = json.RawMessage

type GuardianApprovalReviewStatus string

const (
	GuardianApprovalReviewStatusInProgress GuardianApprovalReviewStatus = "inProgress"
	GuardianApprovalReviewStatusApproved   GuardianApprovalReviewStatus = "approved"
	GuardianApprovalReviewStatusDenied     GuardianApprovalReviewStatus = "denied"
	GuardianApprovalReviewStatusTimedOut   GuardianApprovalReviewStatus = "timedOut"
	GuardianApprovalReviewStatusAborted    GuardianApprovalReviewStatus = "aborted"
)

type GuardianCommandSource string

const (
	GuardianCommandSourceShell       GuardianCommandSource = "shell"
	GuardianCommandSourceUnifiedExec GuardianCommandSource = "unifiedExec"
)

type GuardianRiskLevel string

const (
	GuardianRiskLevelLow      GuardianRiskLevel = "low"
	GuardianRiskLevelMedium   GuardianRiskLevel = "medium"
	GuardianRiskLevelHigh     GuardianRiskLevel = "high"
	GuardianRiskLevelCritical GuardianRiskLevel = "critical"
)

type GuardianUserAuthorization string

const (
	GuardianUserAuthorizationUnknown GuardianUserAuthorization = "unknown"
	GuardianUserAuthorizationLow     GuardianUserAuthorization = "low"
	GuardianUserAuthorizationMedium  GuardianUserAuthorization = "medium"
	GuardianUserAuthorizationHigh    GuardianUserAuthorization = "high"
)

type GuardianWarningNotification struct {
	Message  string `json:"message"`
	ThreadId string `json:"threadId"`
}

type HookCompletedNotification struct {
	Run      HookRunSummary `json:"run"`
	ThreadId string         `json:"threadId"`
	TurnId   *string        `json:"turnId,omitempty"`
}

type HookErrorInfo struct {
	Message string `json:"message"`
	Path    string `json:"path"`
}

type HookEventName string

const (
	HookEventNamePreToolUse        HookEventName = "preToolUse"
	HookEventNamePermissionRequest HookEventName = "permissionRequest"
	HookEventNamePostToolUse       HookEventName = "postToolUse"
	HookEventNamePreCompact        HookEventName = "preCompact"
	HookEventNamePostCompact       HookEventName = "postCompact"
	HookEventNameSessionStart      HookEventName = "sessionStart"
	HookEventNameUserPromptSubmit  HookEventName = "userPromptSubmit"
	HookEventNameStop              HookEventName = "stop"
)

type HookExecutionMode string

const (
	HookExecutionModeSync  HookExecutionMode = "sync"
	HookExecutionModeAsync HookExecutionMode = "async"
)

type HookHandlerType string

const (
	HookHandlerTypeCommand HookHandlerType = "command"
	HookHandlerTypePrompt  HookHandlerType = "prompt"
	HookHandlerTypeAgent   HookHandlerType = "agent"
)

type HookMetadata struct {
	Command       *string         `json:"command,omitempty"`
	CurrentHash   string          `json:"currentHash"`
	DisplayOrder  int64           `json:"displayOrder"`
	Enabled       bool            `json:"enabled"`
	EventName     HookEventName   `json:"eventName"`
	HandlerType   HookHandlerType `json:"handlerType"`
	IsManaged     bool            `json:"isManaged"`
	Key           string          `json:"key"`
	Matcher       *string         `json:"matcher,omitempty"`
	PluginId      *string         `json:"pluginId,omitempty"`
	Source        HookSource      `json:"source"`
	SourcePath    AbsolutePathBuf `json:"sourcePath"`
	StatusMessage *string         `json:"statusMessage,omitempty"`
	TimeoutSec    int64           `json:"timeoutSec"`
	TrustStatus   HookTrustStatus `json:"trustStatus"`
}

type HookMigration struct {
	Name string `json:"name"`
}

type HookOutputEntry struct {
	Kind HookOutputEntryKind `json:"kind"`
	Text string              `json:"text"`
}

type HookOutputEntryKind string

const (
	HookOutputEntryKindWarning  HookOutputEntryKind = "warning"
	HookOutputEntryKindStop     HookOutputEntryKind = "stop"
	HookOutputEntryKindFeedback HookOutputEntryKind = "feedback"
	HookOutputEntryKindContext  HookOutputEntryKind = "context"
	HookOutputEntryKindError    HookOutputEntryKind = "error"
)

type HookPromptFragment struct {
	HookRunId string `json:"hookRunId"`
	Text      string `json:"text"`
}

type HookRunStatus string

const (
	HookRunStatusRunning   HookRunStatus = "running"
	HookRunStatusCompleted HookRunStatus = "completed"
	HookRunStatusFailed    HookRunStatus = "failed"
	HookRunStatusBlocked   HookRunStatus = "blocked"
	HookRunStatusStopped   HookRunStatus = "stopped"
)

type HookRunSummary struct {
	CompletedAt   *int64            `json:"completedAt,omitempty"`
	DisplayOrder  int64             `json:"displayOrder"`
	DurationMs    *int64            `json:"durationMs,omitempty"`
	Entries       []HookOutputEntry `json:"entries"`
	EventName     HookEventName     `json:"eventName"`
	ExecutionMode HookExecutionMode `json:"executionMode"`
	HandlerType   HookHandlerType   `json:"handlerType"`
	ID            string            `json:"id"`
	Scope         HookScope         `json:"scope"`
	Source        json.RawMessage   `json:"source,omitempty"`
	SourcePath    AbsolutePathBuf   `json:"sourcePath"`
	StartedAt     int64             `json:"startedAt"`
	Status        HookRunStatus     `json:"status"`
	StatusMessage *string           `json:"statusMessage,omitempty"`
}

type HookScope string

const (
	HookScopeThread HookScope = "thread"
	HookScopeTurn   HookScope = "turn"
)

type HookSource string

const (
	HookSourceSystem                  HookSource = "system"
	HookSourceUser                    HookSource = "user"
	HookSourceProject                 HookSource = "project"
	HookSourceMdm                     HookSource = "mdm"
	HookSourceSessionFlags            HookSource = "sessionFlags"
	HookSourcePlugin                  HookSource = "plugin"
	HookSourceCloudRequirements       HookSource = "cloudRequirements"
	HookSourceLegacyManagedConfigFile HookSource = "legacyManagedConfigFile"
	HookSourceLegacyManagedConfigMdm  HookSource = "legacyManagedConfigMdm"
	HookSourceUnknown                 HookSource = "unknown"
)

type HookStartedNotification struct {
	Run      HookRunSummary `json:"run"`
	ThreadId string         `json:"threadId"`
	TurnId   *string        `json:"turnId,omitempty"`
}

type HookTrustStatus string

const (
	HookTrustStatusManaged   HookTrustStatus = "managed"
	HookTrustStatusUntrusted HookTrustStatus = "untrusted"
	HookTrustStatusTrusted   HookTrustStatus = "trusted"
	HookTrustStatusModified  HookTrustStatus = "modified"
)

type HooksListEntry struct {
	Cwd      string          `json:"cwd"`
	Errors   []HookErrorInfo `json:"errors"`
	Hooks    []HookMetadata  `json:"hooks"`
	Warnings []string        `json:"warnings"`
}

type HooksListParams struct {
	Cwds []string `json:"cwds,omitempty"`
}

type HooksListResponse struct {
	Data []HooksListEntry `json:"data"`
}

type ImageDetail string

const (
	ImageDetailAuto     ImageDetail = "auto"
	ImageDetailLow      ImageDetail = "low"
	ImageDetailHigh     ImageDetail = "high"
	ImageDetailOriginal ImageDetail = "original"
)

type InputModality = json.RawMessage

type ItemGuardianApprovalReviewCompletedNotification struct {
	Action         GuardianApprovalReviewAction `json:"action"`
	CompletedAtMs  int64                        `json:"completedAtMs"`
	DecisionSource AutoReviewDecisionSource     `json:"decisionSource"`
	Review         GuardianApprovalReview       `json:"review"`
	ReviewId       string                       `json:"reviewId"`
	StartedAtMs    int64                        `json:"startedAtMs"`
	TargetItemId   *string                      `json:"targetItemId,omitempty"`
	ThreadId       string                       `json:"threadId"`
	TurnId         string                       `json:"turnId"`
}

type ItemGuardianApprovalReviewStartedNotification struct {
	Action       GuardianApprovalReviewAction `json:"action"`
	Review       GuardianApprovalReview       `json:"review"`
	ReviewId     string                       `json:"reviewId"`
	StartedAtMs  int64                        `json:"startedAtMs"`
	TargetItemId *string                      `json:"targetItemId,omitempty"`
	ThreadId     string                       `json:"threadId"`
	TurnId       string                       `json:"turnId"`
}

type ItemStartedNotification struct {
	Item        ThreadItem `json:"item"`
	StartedAtMs int64      `json:"startedAtMs"`
	ThreadId    string     `json:"threadId"`
	TurnId      string     `json:"turnId"`
}

type ListMcpServerStatusParams struct {
	Cursor *string                `json:"cursor,omitempty"`
	Detail *McpServerStatusDetail `json:"detail,omitempty"`
	Limit  *int64                 `json:"limit,omitempty"`
}

type ListMcpServerStatusResponse struct {
	Data       []McpServerStatus `json:"data"`
	NextCursor *string           `json:"nextCursor,omitempty"`
}

type LocalShellAction = json.RawMessage

type LocalShellStatus string

const (
	LocalShellStatusCompleted  LocalShellStatus = "completed"
	LocalShellStatusInProgress LocalShellStatus = "in_progress"
	LocalShellStatusIncomplete LocalShellStatus = "incomplete"
)

type LoginAccountParams = json.RawMessage

type LoginAccountResponse = json.RawMessage

type LogoutAccountResponse = json.RawMessage

type ManagedHooksRequirements struct {
	PermissionRequest []ConfiguredHookMatcherGroup `json:"PermissionRequest"`
	PostCompact       []ConfiguredHookMatcherGroup `json:"PostCompact"`
	PostToolUse       []ConfiguredHookMatcherGroup `json:"PostToolUse"`
	PreCompact        []ConfiguredHookMatcherGroup `json:"PreCompact"`
	PreToolUse        []ConfiguredHookMatcherGroup `json:"PreToolUse"`
	SessionStart      []ConfiguredHookMatcherGroup `json:"SessionStart"`
	Stop              []ConfiguredHookMatcherGroup `json:"Stop"`
	UserPromptSubmit  []ConfiguredHookMatcherGroup `json:"UserPromptSubmit"`
	ManagedDir        *string                      `json:"managedDir,omitempty"`
	WindowsManagedDir *string                      `json:"windowsManagedDir,omitempty"`
}

type MarketplaceAddParams struct {
	RefName     *string  `json:"refName,omitempty"`
	Source      string   `json:"source"`
	SparsePaths []string `json:"sparsePaths,omitempty"`
}

type MarketplaceAddResponse struct {
	AlreadyAdded    bool            `json:"alreadyAdded"`
	InstalledRoot   AbsolutePathBuf `json:"installedRoot"`
	MarketplaceName string          `json:"marketplaceName"`
}

type MarketplaceInterface struct {
	DisplayName *string `json:"displayName,omitempty"`
}

type MarketplaceLoadErrorInfo struct {
	MarketplacePath AbsolutePathBuf `json:"marketplacePath"`
	Message         string          `json:"message"`
}

type MarketplaceRemoveParams struct {
	MarketplaceName string `json:"marketplaceName"`
}

type MarketplaceRemoveResponse struct {
	InstalledRoot   *AbsolutePathBuf `json:"installedRoot,omitempty"`
	MarketplaceName string           `json:"marketplaceName"`
}

type MarketplaceUpgradeErrorInfo struct {
	MarketplaceName string `json:"marketplaceName"`
	Message         string `json:"message"`
}

type MarketplaceUpgradeParams struct {
	MarketplaceName *string `json:"marketplaceName,omitempty"`
}

type MarketplaceUpgradeResponse struct {
	Errors               []MarketplaceUpgradeErrorInfo `json:"errors"`
	SelectedMarketplaces []string                      `json:"selectedMarketplaces"`
	UpgradedRoots        []AbsolutePathBuf             `json:"upgradedRoots"`
}

type McpAuthStatus string

const (
	McpAuthStatusUnsupported McpAuthStatus = "unsupported"
	McpAuthStatusNotLoggedIn McpAuthStatus = "notLoggedIn"
	McpAuthStatusBearerToken McpAuthStatus = "bearerToken"
	McpAuthStatusOAuth       McpAuthStatus = "oAuth"
)

type McpResourceReadParams struct {
	Server   string  `json:"server"`
	ThreadId *string `json:"threadId,omitempty"`
	Uri      string  `json:"uri"`
}

type McpResourceReadResponse struct {
	Contents []ResourceContent `json:"contents"`
}

type McpServerMigration struct {
	Name string `json:"name"`
}

type McpServerOauthLoginCompletedNotification struct {
	Error   *string `json:"error,omitempty"`
	Name    string  `json:"name"`
	Success bool    `json:"success"`
}

type McpServerOauthLoginParams struct {
	Name        string   `json:"name"`
	Scopes      []string `json:"scopes,omitempty"`
	TimeoutSecs *int64   `json:"timeoutSecs,omitempty"`
}

type McpServerOauthLoginResponse struct {
	AuthorizationUrl string `json:"authorizationUrl"`
}

type McpServerRefreshResponse = json.RawMessage

type McpServerStartupState string

const (
	McpServerStartupStateStarting  McpServerStartupState = "starting"
	McpServerStartupStateReady     McpServerStartupState = "ready"
	McpServerStartupStateFailed    McpServerStartupState = "failed"
	McpServerStartupStateCancelled McpServerStartupState = "cancelled"
)

type McpServerStatus struct {
	AuthStatus        McpAuthStatus      `json:"authStatus"`
	Name              string             `json:"name"`
	ResourceTemplates []ResourceTemplate `json:"resourceTemplates"`
	Resources         []Resource         `json:"resources"`
	Tools             map[string]Tool    `json:"tools"`
}

type McpServerStatusDetail string

const (
	McpServerStatusDetailFull             McpServerStatusDetail = "full"
	McpServerStatusDetailToolsAndAuthOnly McpServerStatusDetail = "toolsAndAuthOnly"
)

type McpServerStatusUpdatedNotification struct {
	Error  *string               `json:"error,omitempty"`
	Name   string                `json:"name"`
	Status McpServerStartupState `json:"status"`
}

type McpServerToolCallParams struct {
	Meta      map[string]any `json:"_meta,omitempty"`
	Arguments map[string]any `json:"arguments,omitempty"`
	Server    string         `json:"server"`
	ThreadId  string         `json:"threadId"`
	Tool      string         `json:"tool"`
}

type McpServerToolCallResponse struct {
	Meta              map[string]any   `json:"_meta,omitempty"`
	Content           []map[string]any `json:"content"`
	IsError           *bool            `json:"isError,omitempty"`
	StructuredContent map[string]any   `json:"structuredContent,omitempty"`
}

type McpToolCallError struct {
	Message string `json:"message"`
}

type McpToolCallProgressNotification struct {
	ItemId   string `json:"itemId"`
	Message  string `json:"message"`
	ThreadId string `json:"threadId"`
	TurnId   string `json:"turnId"`
}

type McpToolCallResult struct {
	Meta              map[string]any   `json:"_meta,omitempty"`
	Content           []map[string]any `json:"content"`
	StructuredContent map[string]any   `json:"structuredContent,omitempty"`
}

type McpToolCallStatus string

const (
	McpToolCallStatusInProgress McpToolCallStatus = "inProgress"
	McpToolCallStatusCompleted  McpToolCallStatus = "completed"
	McpToolCallStatusFailed     McpToolCallStatus = "failed"
)

type MemoryCitation struct {
	Entries   []MemoryCitationEntry `json:"entries"`
	ThreadIds []string              `json:"threadIds"`
}

type MemoryCitationEntry struct {
	LineEnd   int64  `json:"lineEnd"`
	LineStart int64  `json:"lineStart"`
	Note      string `json:"note"`
	Path      string `json:"path"`
}

type MergeStrategy string

const (
	MergeStrategyReplace MergeStrategy = "replace"
	MergeStrategyUpsert  MergeStrategy = "upsert"
)

type MigrationDetails struct {
	Commands   []CommandMigration   `json:"commands,omitempty"`
	Hooks      []HookMigration      `json:"hooks,omitempty"`
	McpServers []McpServerMigration `json:"mcpServers,omitempty"`
	Plugins    []PluginsMigration   `json:"plugins,omitempty"`
	Sessions   []SessionMigration   `json:"sessions,omitempty"`
	Subagents  []SubagentMigration  `json:"subagents,omitempty"`
}

type ModeKind string

const (
	ModeKindPlan    ModeKind = "plan"
	ModeKindDefault ModeKind = "default"
)

type ModelAvailabilityNux struct {
	Message string `json:"message"`
}

type ModelListParams struct {
	Cursor        *string `json:"cursor,omitempty"`
	IncludeHidden *bool   `json:"includeHidden,omitempty"`
	Limit         *int64  `json:"limit,omitempty"`
}

type ModelProviderCapabilitiesReadParams = json.RawMessage

type ModelProviderCapabilitiesReadResponse struct {
	ImageGeneration bool `json:"imageGeneration"`
	NamespaceTools  bool `json:"namespaceTools"`
	WebSearch       bool `json:"webSearch"`
}

type ModelRerouteReason string

const (
	ModelRerouteReasonHighRiskCyberActivity ModelRerouteReason = "highRiskCyberActivity"
)

type ModelReroutedNotification struct {
	FromModel string             `json:"fromModel"`
	Reason    ModelRerouteReason `json:"reason"`
	ThreadId  string             `json:"threadId"`
	ToModel   string             `json:"toModel"`
	TurnId    string             `json:"turnId"`
}

type ModelServiceTier struct {
	Description string `json:"description"`
	ID          string `json:"id"`
	Name        string `json:"name"`
}

type ModelUpgradeInfo struct {
	MigrationMarkdown *string `json:"migrationMarkdown,omitempty"`
	Model             string  `json:"model"`
	ModelLink         *string `json:"modelLink,omitempty"`
	UpgradeCopy       *string `json:"upgradeCopy,omitempty"`
}

type ModelVerification string

const (
	ModelVerificationTrustedAccessForCyber ModelVerification = "trustedAccessForCyber"
)

type ModelVerificationNotification struct {
	ThreadId      string              `json:"threadId"`
	TurnId        string              `json:"turnId"`
	Verifications []ModelVerification `json:"verifications"`
}

type NetworkAccess string

const (
	NetworkAccessRestricted NetworkAccess = "restricted"
	NetworkAccessEnabled    NetworkAccess = "enabled"
)

type NetworkApprovalProtocol string

const (
	NetworkApprovalProtocolHttp      NetworkApprovalProtocol = "http"
	NetworkApprovalProtocolHttps     NetworkApprovalProtocol = "https"
	NetworkApprovalProtocolSocks5Tcp NetworkApprovalProtocol = "socks5Tcp"
	NetworkApprovalProtocolSocks5Udp NetworkApprovalProtocol = "socks5Udp"
)

type NetworkDomainPermission string

const (
	NetworkDomainPermissionAllow NetworkDomainPermission = "allow"
	NetworkDomainPermissionDeny  NetworkDomainPermission = "deny"
)

type NetworkRequirements struct {
	AllowLocalBinding                *bool                                  `json:"allowLocalBinding,omitempty"`
	AllowUnixSockets                 []string                               `json:"allowUnixSockets,omitempty"`
	AllowUpstreamProxy               *bool                                  `json:"allowUpstreamProxy,omitempty"`
	AllowedDomains                   []string                               `json:"allowedDomains,omitempty"`
	DangerouslyAllowAllUnixSockets   *bool                                  `json:"dangerouslyAllowAllUnixSockets,omitempty"`
	DangerouslyAllowNonLoopbackProxy *bool                                  `json:"dangerouslyAllowNonLoopbackProxy,omitempty"`
	DeniedDomains                    []string                               `json:"deniedDomains,omitempty"`
	Domains                          map[string]NetworkDomainPermission     `json:"domains,omitempty"`
	Enabled                          *bool                                  `json:"enabled,omitempty"`
	HttpPort                         *int64                                 `json:"httpPort,omitempty"`
	ManagedAllowedDomainsOnly        *bool                                  `json:"managedAllowedDomainsOnly,omitempty"`
	SocksPort                        *int64                                 `json:"socksPort,omitempty"`
	UnixSockets                      map[string]NetworkUnixSocketPermission `json:"unixSockets,omitempty"`
}

type NetworkUnixSocketPermission string

const (
	NetworkUnixSocketPermissionAllow NetworkUnixSocketPermission = "allow"
	NetworkUnixSocketPermissionNone  NetworkUnixSocketPermission = "none"
)

type NonSteerableTurnKind string

const (
	NonSteerableTurnKindReview  NonSteerableTurnKind = "review"
	NonSteerableTurnKindCompact NonSteerableTurnKind = "compact"
)

type OverriddenMetadata struct {
	EffectiveValue  map[string]any      `json:"effectiveValue"`
	Message         string              `json:"message"`
	OverridingLayer ConfigLayerMetadata `json:"overridingLayer"`
}

type PatchApplyStatus string

const (
	PatchApplyStatusInProgress PatchApplyStatus = "inProgress"
	PatchApplyStatusCompleted  PatchApplyStatus = "completed"
	PatchApplyStatusFailed     PatchApplyStatus = "failed"
	PatchApplyStatusDeclined   PatchApplyStatus = "declined"
)

type PatchChangeKind = json.RawMessage

type PermissionProfile = json.RawMessage

type PermissionProfileFileSystemPermissions = json.RawMessage

type PermissionProfileModificationParams = json.RawMessage

type PermissionProfileNetworkPermissions struct {
	Enabled bool `json:"enabled"`
}

type PermissionProfileSelectionParams = json.RawMessage

type PlanDeltaNotification struct {
	Delta    string `json:"delta"`
	ItemId   string `json:"itemId"`
	ThreadId string `json:"threadId"`
	TurnId   string `json:"turnId"`
}

type PlanType string

const (
	PlanTypeFree                        PlanType = "free"
	PlanTypeGo                          PlanType = "go"
	PlanTypePlus                        PlanType = "plus"
	PlanTypePro                         PlanType = "pro"
	PlanTypeProlite                     PlanType = "prolite"
	PlanTypeTeam                        PlanType = "team"
	PlanTypeSelfServeBusinessUsageBased PlanType = "self_serve_business_usage_based"
	PlanTypeBusiness                    PlanType = "business"
	PlanTypeEnterpriseCbpUsageBased     PlanType = "enterprise_cbp_usage_based"
	PlanTypeEnterprise                  PlanType = "enterprise"
	PlanTypeEdu                         PlanType = "edu"
	PlanTypeUnknown                     PlanType = "unknown"
)

type PluginAuthPolicy string

const (
	PluginAuthPolicyONINSTALL PluginAuthPolicy = "ON_INSTALL"
	PluginAuthPolicyONUSE     PluginAuthPolicy = "ON_USE"
)

type PluginAvailability = json.RawMessage

type PluginDetail struct {
	Apps            []AppSummary        `json:"apps"`
	Description     *string             `json:"description,omitempty"`
	Hooks           []PluginHookSummary `json:"hooks"`
	MarketplaceName string              `json:"marketplaceName"`
	MarketplacePath *AbsolutePathBuf    `json:"marketplacePath,omitempty"`
	McpServers      []string            `json:"mcpServers"`
	Skills          []SkillSummary      `json:"skills"`
	Summary         PluginSummary       `json:"summary"`
}

type PluginHookSummary struct {
	EventName HookEventName `json:"eventName"`
	Key       string        `json:"key"`
}

type PluginInstallParams struct {
	MarketplacePath       *AbsolutePathBuf `json:"marketplacePath,omitempty"`
	PluginName            string           `json:"pluginName"`
	RemoteMarketplaceName *string          `json:"remoteMarketplaceName,omitempty"`
}

type PluginInstallPolicy string

const (
	PluginInstallPolicyNOTAVAILABLE       PluginInstallPolicy = "NOT_AVAILABLE"
	PluginInstallPolicyAVAILABLE          PluginInstallPolicy = "AVAILABLE"
	PluginInstallPolicyINSTALLEDBYDEFAULT PluginInstallPolicy = "INSTALLED_BY_DEFAULT"
)

type PluginInstallResponse struct {
	AppsNeedingAuth []AppSummary     `json:"appsNeedingAuth"`
	AuthPolicy      PluginAuthPolicy `json:"authPolicy"`
}

type PluginInterface struct {
	BrandColor        *string           `json:"brandColor,omitempty"`
	Capabilities      []string          `json:"capabilities"`
	Category          *string           `json:"category,omitempty"`
	ComposerIcon      *AbsolutePathBuf  `json:"composerIcon,omitempty"`
	ComposerIconUrl   *string           `json:"composerIconUrl,omitempty"`
	DefaultPrompt     []string          `json:"defaultPrompt,omitempty"`
	DeveloperName     *string           `json:"developerName,omitempty"`
	DisplayName       *string           `json:"displayName,omitempty"`
	Logo              *AbsolutePathBuf  `json:"logo,omitempty"`
	LogoUrl           *string           `json:"logoUrl,omitempty"`
	LongDescription   *string           `json:"longDescription,omitempty"`
	PrivacyPolicyUrl  *string           `json:"privacyPolicyUrl,omitempty"`
	ScreenshotUrls    []string          `json:"screenshotUrls"`
	Screenshots       []AbsolutePathBuf `json:"screenshots"`
	ShortDescription  *string           `json:"shortDescription,omitempty"`
	TermsOfServiceUrl *string           `json:"termsOfServiceUrl,omitempty"`
	WebsiteUrl        *string           `json:"websiteUrl,omitempty"`
}

type PluginListMarketplaceKind string

const (
	PluginListMarketplaceKindLocal              PluginListMarketplaceKind = "local"
	PluginListMarketplaceKindWorkspaceDirectory PluginListMarketplaceKind = "workspace-directory"
	PluginListMarketplaceKindSharedWithMe       PluginListMarketplaceKind = "shared-with-me"
)

type PluginListParams struct {
	Cwds             []AbsolutePathBuf           `json:"cwds,omitempty"`
	MarketplaceKinds []PluginListMarketplaceKind `json:"marketplaceKinds,omitempty"`
}

type PluginListResponse struct {
	FeaturedPluginIds     []string                   `json:"featuredPluginIds,omitempty"`
	MarketplaceLoadErrors []MarketplaceLoadErrorInfo `json:"marketplaceLoadErrors,omitempty"`
	Marketplaces          []PluginMarketplaceEntry   `json:"marketplaces"`
}

type PluginMarketplaceEntry struct {
	Interface *MarketplaceInterface `json:"interface,omitempty"`
	Name      string                `json:"name"`
	Path      *AbsolutePathBuf      `json:"path,omitempty"`
	Plugins   []PluginSummary       `json:"plugins"`
}

type PluginReadParams struct {
	MarketplacePath       *AbsolutePathBuf `json:"marketplacePath,omitempty"`
	PluginName            string           `json:"pluginName"`
	RemoteMarketplaceName *string          `json:"remoteMarketplaceName,omitempty"`
}

type PluginReadResponse struct {
	Plugin PluginDetail `json:"plugin"`
}

type PluginShareContext struct {
	CreatorAccountUserId *string                `json:"creatorAccountUserId,omitempty"`
	CreatorName          *string                `json:"creatorName,omitempty"`
	RemotePluginId       string                 `json:"remotePluginId"`
	ShareTargets         []PluginSharePrincipal `json:"shareTargets,omitempty"`
	ShareUrl             *string                `json:"shareUrl,omitempty"`
}

type PluginShareDeleteParams struct {
	RemotePluginId string `json:"remotePluginId"`
}

type PluginShareDeleteResponse = json.RawMessage

type PluginShareDiscoverability string

const (
	PluginShareDiscoverabilityLISTED   PluginShareDiscoverability = "LISTED"
	PluginShareDiscoverabilityUNLISTED PluginShareDiscoverability = "UNLISTED"
	PluginShareDiscoverabilityPRIVATE  PluginShareDiscoverability = "PRIVATE"
)

type PluginShareListItem struct {
	LocalPluginPath *AbsolutePathBuf `json:"localPluginPath,omitempty"`
	Plugin          PluginSummary    `json:"plugin"`
	ShareUrl        string           `json:"shareUrl"`
}

type PluginShareListParams = json.RawMessage

type PluginShareListResponse struct {
	Data []PluginShareListItem `json:"data"`
}

type PluginSharePrincipal struct {
	Name          string                   `json:"name"`
	PrincipalId   string                   `json:"principalId"`
	PrincipalType PluginSharePrincipalType `json:"principalType"`
}

type PluginSharePrincipalType string

const (
	PluginSharePrincipalTypeUser      PluginSharePrincipalType = "user"
	PluginSharePrincipalTypeGroup     PluginSharePrincipalType = "group"
	PluginSharePrincipalTypeWorkspace PluginSharePrincipalType = "workspace"
)

type PluginShareSaveParams struct {
	Discoverability *PluginShareDiscoverability `json:"discoverability,omitempty"`
	PluginPath      AbsolutePathBuf             `json:"pluginPath"`
	RemotePluginId  *string                     `json:"remotePluginId,omitempty"`
	ShareTargets    []PluginShareTarget         `json:"shareTargets,omitempty"`
}

type PluginShareSaveResponse struct {
	RemotePluginId string `json:"remotePluginId"`
	ShareUrl       string `json:"shareUrl"`
}

type PluginShareTarget struct {
	PrincipalId   string                   `json:"principalId"`
	PrincipalType PluginSharePrincipalType `json:"principalType"`
}

type PluginShareUpdateDiscoverability string

const (
	PluginShareUpdateDiscoverabilityUNLISTED PluginShareUpdateDiscoverability = "UNLISTED"
	PluginShareUpdateDiscoverabilityPRIVATE  PluginShareUpdateDiscoverability = "PRIVATE"
)

type PluginShareUpdateTargetsParams struct {
	Discoverability PluginShareUpdateDiscoverability `json:"discoverability"`
	RemotePluginId  string                           `json:"remotePluginId"`
	ShareTargets    []PluginShareTarget              `json:"shareTargets"`
}

type PluginShareUpdateTargetsResponse struct {
	Discoverability PluginShareDiscoverability `json:"discoverability"`
	Principals      []PluginSharePrincipal     `json:"principals"`
}

type PluginSkillReadParams struct {
	RemoteMarketplaceName string `json:"remoteMarketplaceName"`
	RemotePluginId        string `json:"remotePluginId"`
	SkillName             string `json:"skillName"`
}

type PluginSkillReadResponse struct {
	Contents *string `json:"contents,omitempty"`
}

type PluginSource = json.RawMessage

type PluginSummary struct {
	AuthPolicy    PluginAuthPolicy    `json:"authPolicy"`
	Availability  json.RawMessage     `json:"availability,omitempty"`
	Enabled       bool                `json:"enabled"`
	ID            string              `json:"id"`
	InstallPolicy PluginInstallPolicy `json:"installPolicy"`
	Installed     bool                `json:"installed"`
	Interface     *PluginInterface    `json:"interface,omitempty"`
	Keywords      []string            `json:"keywords,omitempty"`
	Name          string              `json:"name"`
	ShareContext  *PluginShareContext `json:"shareContext,omitempty"`
	Source        PluginSource        `json:"source"`
}

type PluginUninstallParams struct {
	PluginId string `json:"pluginId"`
}

type PluginUninstallResponse = json.RawMessage

type PluginsMigration struct {
	MarketplaceName string   `json:"marketplaceName"`
	PluginNames     []string `json:"pluginNames"`
}

type ProcessExitedNotification struct {
	ExitCode         int64  `json:"exitCode"`
	ProcessHandle    string `json:"processHandle"`
	Stderr           string `json:"stderr"`
	StderrCapReached bool   `json:"stderrCapReached"`
	Stdout           string `json:"stdout"`
	StdoutCapReached bool   `json:"stdoutCapReached"`
}

type ProcessOutputDeltaNotification struct {
	CapReached    bool            `json:"capReached"`
	DeltaBase64   string          `json:"deltaBase64"`
	ProcessHandle string          `json:"processHandle"`
	Stream        json.RawMessage `json:"stream"`
}

type ProcessOutputStream = json.RawMessage

type ProcessTerminalSize struct {
	Cols int64 `json:"cols"`
	Rows int64 `json:"rows"`
}

type ProfileV2 struct {
	ApprovalPolicy        *AskForApproval    `json:"approval_policy,omitempty"`
	ApprovalsReviewer     *ApprovalsReviewer `json:"approvals_reviewer,omitempty"`
	ChatgptBaseURL        *string            `json:"chatgpt_base_url,omitempty"`
	Model                 *string            `json:"model,omitempty"`
	ModelProvider         *string            `json:"model_provider,omitempty"`
	ModelReasoningEffort  *ReasoningEffort   `json:"model_reasoning_effort,omitempty"`
	ModelReasoningSummary *ReasoningSummary  `json:"model_reasoning_summary,omitempty"`
	ModelVerbosity        *Verbosity         `json:"model_verbosity,omitempty"`
	ServiceTier           *string            `json:"service_tier,omitempty"`
	Tools                 *ToolsV2           `json:"tools,omitempty"`
	WebSearch             *WebSearchMode     `json:"web_search,omitempty"`
}

type RateLimitReachedType string

const (
	RateLimitReachedTypeRateLimitReached                 RateLimitReachedType = "rate_limit_reached"
	RateLimitReachedTypeWorkspaceOwnerCreditsDepleted    RateLimitReachedType = "workspace_owner_credits_depleted"
	RateLimitReachedTypeWorkspaceMemberCreditsDepleted   RateLimitReachedType = "workspace_member_credits_depleted"
	RateLimitReachedTypeWorkspaceOwnerUsageLimitReached  RateLimitReachedType = "workspace_owner_usage_limit_reached"
	RateLimitReachedTypeWorkspaceMemberUsageLimitReached RateLimitReachedType = "workspace_member_usage_limit_reached"
)

type RateLimitSnapshot struct {
	Credits              *CreditsSnapshot      `json:"credits,omitempty"`
	LimitId              *string               `json:"limitId,omitempty"`
	LimitName            *string               `json:"limitName,omitempty"`
	PlanType             *PlanType             `json:"planType,omitempty"`
	Primary              *RateLimitWindow      `json:"primary,omitempty"`
	RateLimitReachedType *RateLimitReachedType `json:"rateLimitReachedType,omitempty"`
	Secondary            *RateLimitWindow      `json:"secondary,omitempty"`
}

type RateLimitWindow struct {
	ResetsAt           *int64 `json:"resetsAt,omitempty"`
	UsedPercent        int64  `json:"usedPercent"`
	WindowDurationMins *int64 `json:"windowDurationMins,omitempty"`
}

type RawResponseItemCompletedNotification struct {
	Item     ResponseItem `json:"item"`
	ThreadId string       `json:"threadId"`
	TurnId   string       `json:"turnId"`
}

type RealtimeConversationVersion string

const (
	RealtimeConversationVersionV1 RealtimeConversationVersion = "v1"
	RealtimeConversationVersionV2 RealtimeConversationVersion = "v2"
)

type RealtimeOutputModality string

const (
	RealtimeOutputModalityText  RealtimeOutputModality = "text"
	RealtimeOutputModalityAudio RealtimeOutputModality = "audio"
)

type RealtimeVoice string

const (
	RealtimeVoiceAlloy   RealtimeVoice = "alloy"
	RealtimeVoiceArbor   RealtimeVoice = "arbor"
	RealtimeVoiceAsh     RealtimeVoice = "ash"
	RealtimeVoiceBallad  RealtimeVoice = "ballad"
	RealtimeVoiceBreeze  RealtimeVoice = "breeze"
	RealtimeVoiceCedar   RealtimeVoice = "cedar"
	RealtimeVoiceCoral   RealtimeVoice = "coral"
	RealtimeVoiceCove    RealtimeVoice = "cove"
	RealtimeVoiceEcho    RealtimeVoice = "echo"
	RealtimeVoiceEmber   RealtimeVoice = "ember"
	RealtimeVoiceJuniper RealtimeVoice = "juniper"
	RealtimeVoiceMaple   RealtimeVoice = "maple"
	RealtimeVoiceMarin   RealtimeVoice = "marin"
	RealtimeVoiceSage    RealtimeVoice = "sage"
	RealtimeVoiceShimmer RealtimeVoice = "shimmer"
	RealtimeVoiceSol     RealtimeVoice = "sol"
	RealtimeVoiceSpruce  RealtimeVoice = "spruce"
	RealtimeVoiceVale    RealtimeVoice = "vale"
	RealtimeVoiceVerse   RealtimeVoice = "verse"
)

type RealtimeVoicesList struct {
	DefaultV1 RealtimeVoice   `json:"defaultV1"`
	DefaultV2 RealtimeVoice   `json:"defaultV2"`
	V1        []RealtimeVoice `json:"v1"`
	V2        []RealtimeVoice `json:"v2"`
}

type ReasoningEffortOption struct {
	Description     string          `json:"description"`
	ReasoningEffort ReasoningEffort `json:"reasoningEffort"`
}

type ReasoningItemContent = json.RawMessage

type ReasoningItemReasoningSummary = json.RawMessage

type ReasoningSummaryPartAddedNotification struct {
	ItemId       string `json:"itemId"`
	SummaryIndex int64  `json:"summaryIndex"`
	ThreadId     string `json:"threadId"`
	TurnId       string `json:"turnId"`
}

type ReasoningSummaryTextDeltaNotification struct {
	Delta        string `json:"delta"`
	ItemId       string `json:"itemId"`
	SummaryIndex int64  `json:"summaryIndex"`
	ThreadId     string `json:"threadId"`
	TurnId       string `json:"turnId"`
}

type ReasoningTextDeltaNotification struct {
	ContentIndex int64  `json:"contentIndex"`
	Delta        string `json:"delta"`
	ItemId       string `json:"itemId"`
	ThreadId     string `json:"threadId"`
	TurnId       string `json:"turnId"`
}

type RemoteControlConnectionStatus string

const (
	RemoteControlConnectionStatusDisabled   RemoteControlConnectionStatus = "disabled"
	RemoteControlConnectionStatusConnecting RemoteControlConnectionStatus = "connecting"
	RemoteControlConnectionStatusConnected  RemoteControlConnectionStatus = "connected"
	RemoteControlConnectionStatusErrored    RemoteControlConnectionStatus = "errored"
)

type RemoteControlStatusChangedNotification struct {
	EnvironmentId  *string                       `json:"environmentId,omitempty"`
	InstallationId string                        `json:"installationId"`
	Status         RemoteControlConnectionStatus `json:"status"`
}

type RequestPermissionProfile struct {
	FileSystem *AdditionalFileSystemPermissions `json:"fileSystem,omitempty"`
	Network    *AdditionalNetworkPermissions    `json:"network,omitempty"`
}

type ResidencyRequirement string

const (
	ResidencyRequirementUs ResidencyRequirement = "us"
)

type Resource struct {
	Meta        map[string]any   `json:"_meta,omitempty"`
	Annotations map[string]any   `json:"annotations,omitempty"`
	Description *string          `json:"description,omitempty"`
	Icons       []map[string]any `json:"icons,omitempty"`
	MimeType    *string          `json:"mimeType,omitempty"`
	Name        string           `json:"name"`
	Size        *int64           `json:"size,omitempty"`
	Title       *string          `json:"title,omitempty"`
	Uri         string           `json:"uri"`
}

type ResourceTemplate struct {
	Annotations map[string]any `json:"annotations,omitempty"`
	Description *string        `json:"description,omitempty"`
	MimeType    *string        `json:"mimeType,omitempty"`
	Name        string         `json:"name"`
	Title       *string        `json:"title,omitempty"`
	UriTemplate string         `json:"uriTemplate"`
}

type ResponseItem = json.RawMessage

type ResponsesApiWebSearchAction = json.RawMessage

type ReviewDelivery string

const (
	ReviewDeliveryInline   ReviewDelivery = "inline"
	ReviewDeliveryDetached ReviewDelivery = "detached"
)

type ReviewStartParams struct {
	Delivery *ReviewDelivery `json:"delivery,omitempty"`
	Target   ReviewTarget    `json:"target"`
	ThreadId string          `json:"threadId"`
}

type ReviewStartResponse struct {
	ReviewThreadId string `json:"reviewThreadId"`
	Turn           Turn   `json:"turn"`
}

type ReviewTarget = json.RawMessage

type SandboxWorkspaceWrite struct {
	ExcludeSlashTmp     *bool    `json:"exclude_slash_tmp,omitempty"`
	ExcludeTmpdirEnvVar *bool    `json:"exclude_tmpdir_env_var,omitempty"`
	NetworkAccess       *bool    `json:"network_access,omitempty"`
	WritableRoots       []string `json:"writable_roots,omitempty"`
}

type SendAddCreditsNudgeEmailParams struct {
	CreditType AddCreditsNudgeCreditType `json:"creditType"`
}

type SendAddCreditsNudgeEmailResponse struct {
	Status AddCreditsNudgeEmailStatus `json:"status"`
}

type ServerNotification = json.RawMessage

type ServerRequestResolvedNotification struct {
	RequestId RequestId `json:"requestId"`
	ThreadId  string    `json:"threadId"`
}

type SessionMigration struct {
	Cwd   string  `json:"cwd"`
	Path  string  `json:"path"`
	Title *string `json:"title,omitempty"`
}

type SessionSource = json.RawMessage

type Settings struct {
	DeveloperInstructions *string          `json:"developer_instructions,omitempty"`
	Model                 string           `json:"model"`
	ReasoningEffort       *ReasoningEffort `json:"reasoning_effort,omitempty"`
}

type SkillDependencies struct {
	Tools []SkillToolDependency `json:"tools"`
}

type SkillErrorInfo struct {
	Message string `json:"message"`
	Path    string `json:"path"`
}

type SkillInterface struct {
	BrandColor       *string          `json:"brandColor,omitempty"`
	DefaultPrompt    *string          `json:"defaultPrompt,omitempty"`
	DisplayName      *string          `json:"displayName,omitempty"`
	IconLarge        *AbsolutePathBuf `json:"iconLarge,omitempty"`
	IconSmall        *AbsolutePathBuf `json:"iconSmall,omitempty"`
	ShortDescription *string          `json:"shortDescription,omitempty"`
}

type SkillMetadata struct {
	Dependencies     *SkillDependencies `json:"dependencies,omitempty"`
	Description      string             `json:"description"`
	Enabled          bool               `json:"enabled"`
	Interface        *SkillInterface    `json:"interface,omitempty"`
	Name             string             `json:"name"`
	Path             AbsolutePathBuf    `json:"path"`
	Scope            SkillScope         `json:"scope"`
	ShortDescription *string            `json:"shortDescription,omitempty"`
}

type SkillScope string

const (
	SkillScopeUser   SkillScope = "user"
	SkillScopeRepo   SkillScope = "repo"
	SkillScopeSystem SkillScope = "system"
	SkillScopeAdmin  SkillScope = "admin"
)

type SkillSummary struct {
	Description      string           `json:"description"`
	Enabled          bool             `json:"enabled"`
	Interface        *SkillInterface  `json:"interface,omitempty"`
	Name             string           `json:"name"`
	Path             *AbsolutePathBuf `json:"path,omitempty"`
	ShortDescription *string          `json:"shortDescription,omitempty"`
}

type SkillToolDependency struct {
	Command     *string `json:"command,omitempty"`
	Description *string `json:"description,omitempty"`
	Transport   *string `json:"transport,omitempty"`
	Type        string  `json:"type"`
	URL         *string `json:"url,omitempty"`
	Value       string  `json:"value"`
}

type SkillsChangedNotification = json.RawMessage

type SkillsConfigWriteParams struct {
	Enabled bool             `json:"enabled"`
	Name    *string          `json:"name,omitempty"`
	Path    *AbsolutePathBuf `json:"path,omitempty"`
}

type SkillsConfigWriteResponse struct {
	EffectiveEnabled bool `json:"effectiveEnabled"`
}

type SkillsListEntry struct {
	Cwd    string           `json:"cwd"`
	Errors []SkillErrorInfo `json:"errors"`
	Skills []SkillMetadata  `json:"skills"`
}

type SkillsListParams struct {
	Cwds        []string `json:"cwds,omitempty"`
	ForceReload *bool    `json:"forceReload,omitempty"`
}

type SkillsListResponse struct {
	Data []SkillsListEntry `json:"data"`
}

type SortDirection string

const (
	SortDirectionAsc  SortDirection = "asc"
	SortDirectionDesc SortDirection = "desc"
)

type SubAgentSource = json.RawMessage

type SubagentMigration struct {
	Name string `json:"name"`
}

type TerminalInteractionNotification struct {
	ItemId    string `json:"itemId"`
	ProcessId string `json:"processId"`
	Stdin     string `json:"stdin"`
	ThreadId  string `json:"threadId"`
	TurnId    string `json:"turnId"`
}

type TextElement struct {
	ByteRange   json.RawMessage `json:"byteRange"`
	Placeholder *string         `json:"placeholder,omitempty"`
}

type TextPosition struct {
	Column int64 `json:"column"`
	Line   int64 `json:"line"`
}

type TextRange struct {
	End   TextPosition `json:"end"`
	Start TextPosition `json:"start"`
}

type ThreadActiveFlag string

const (
	ThreadActiveFlagWaitingOnApproval  ThreadActiveFlag = "waitingOnApproval"
	ThreadActiveFlagWaitingOnUserInput ThreadActiveFlag = "waitingOnUserInput"
)

type ThreadApproveGuardianDeniedActionParams struct {
	Event    json.RawMessage `json:"event"`
	ThreadId string          `json:"threadId"`
}

type ThreadApproveGuardianDeniedActionResponse = json.RawMessage

type ThreadArchiveParams struct {
	ThreadId string `json:"threadId"`
}

type ThreadArchivedNotification struct {
	ThreadId string `json:"threadId"`
}

type ThreadClosedNotification struct {
	ThreadId string `json:"threadId"`
}

type ThreadCompactStartParams struct {
	ThreadId string `json:"threadId"`
}

type ThreadGoal struct {
	CreatedAt       int64            `json:"createdAt"`
	Objective       string           `json:"objective"`
	Status          ThreadGoalStatus `json:"status"`
	ThreadId        string           `json:"threadId"`
	TimeUsedSeconds int64            `json:"timeUsedSeconds"`
	TokenBudget     *int64           `json:"tokenBudget,omitempty"`
	TokensUsed      int64            `json:"tokensUsed"`
	UpdatedAt       int64            `json:"updatedAt"`
}

type ThreadGoalClearedNotification struct {
	ThreadId string `json:"threadId"`
}

type ThreadGoalStatus string

const (
	ThreadGoalStatusActive        ThreadGoalStatus = "active"
	ThreadGoalStatusPaused        ThreadGoalStatus = "paused"
	ThreadGoalStatusBudgetLimited ThreadGoalStatus = "budgetLimited"
	ThreadGoalStatusComplete      ThreadGoalStatus = "complete"
)

type ThreadGoalUpdatedNotification struct {
	Goal     ThreadGoal `json:"goal"`
	ThreadId string     `json:"threadId"`
	TurnId   *string    `json:"turnId,omitempty"`
}

type ThreadId = string

type ThreadInjectItemsParams struct {
	Items    []map[string]any `json:"items"`
	ThreadId string           `json:"threadId"`
}

type ThreadListCwdFilter = json.RawMessage

type ThreadLoadedListParams struct {
	Cursor *string `json:"cursor,omitempty"`
	Limit  *int64  `json:"limit,omitempty"`
}

type ThreadLoadedListResponse struct {
	Data       []string `json:"data"`
	NextCursor *string  `json:"nextCursor,omitempty"`
}

type ThreadMemoryMode string

const (
	ThreadMemoryModeEnabled  ThreadMemoryMode = "enabled"
	ThreadMemoryModeDisabled ThreadMemoryMode = "disabled"
)

type ThreadMetadataGitInfoUpdateParams struct {
	Branch    *string `json:"branch,omitempty"`
	OriginUrl *string `json:"originUrl,omitempty"`
	Sha       *string `json:"sha,omitempty"`
}

type ThreadMetadataUpdateParams struct {
	GitInfo  *ThreadMetadataGitInfoUpdateParams `json:"gitInfo,omitempty"`
	ThreadId string                             `json:"threadId"`
}

type ThreadMetadataUpdateResponse struct {
	Thread Thread `json:"thread"`
}

type ThreadNameUpdatedNotification struct {
	ThreadId   string  `json:"threadId"`
	ThreadName *string `json:"threadName,omitempty"`
}

type ThreadReadParams struct {
	IncludeTurns *bool  `json:"includeTurns,omitempty"`
	ThreadId     string `json:"threadId"`
}

type ThreadRealtimeAudioChunk struct {
	Data              string  `json:"data"`
	ItemId            *string `json:"itemId,omitempty"`
	NumChannels       int64   `json:"numChannels"`
	SampleRate        int64   `json:"sampleRate"`
	SamplesPerChannel *int64  `json:"samplesPerChannel,omitempty"`
}

type ThreadRealtimeClosedNotification struct {
	Reason   *string `json:"reason,omitempty"`
	ThreadId string  `json:"threadId"`
}

type ThreadRealtimeErrorNotification struct {
	Message  string `json:"message"`
	ThreadId string `json:"threadId"`
}

type ThreadRealtimeItemAddedNotification struct {
	Item     map[string]any `json:"item"`
	ThreadId string         `json:"threadId"`
}

type ThreadRealtimeOutputAudioDeltaNotification struct {
	Audio    ThreadRealtimeAudioChunk `json:"audio"`
	ThreadId string                   `json:"threadId"`
}

type ThreadRealtimeSdpNotification struct {
	Sdp      string `json:"sdp"`
	ThreadId string `json:"threadId"`
}

type ThreadRealtimeStartedNotification struct {
	RealtimeSessionId *string                     `json:"realtimeSessionId,omitempty"`
	ThreadId          string                      `json:"threadId"`
	Version           RealtimeConversationVersion `json:"version"`
}

type ThreadRealtimeTranscriptDeltaNotification struct {
	Delta    string `json:"delta"`
	Role     string `json:"role"`
	ThreadId string `json:"threadId"`
}

type ThreadRealtimeTranscriptDoneNotification struct {
	Role     string `json:"role"`
	Text     string `json:"text"`
	ThreadId string `json:"threadId"`
}

type ThreadRollbackParams struct {
	NumTurns int64  `json:"numTurns"`
	ThreadId string `json:"threadId"`
}

type ThreadRollbackResponse struct {
	Thread json.RawMessage `json:"thread"`
}

type ThreadSetNameParams struct {
	Name     string `json:"name"`
	ThreadId string `json:"threadId"`
}

type ThreadShellCommandParams struct {
	Command  string `json:"command"`
	ThreadId string `json:"threadId"`
}

type ThreadShellCommandResponse = json.RawMessage

type ThreadSource string

const (
	ThreadSourceUser                ThreadSource = "user"
	ThreadSourceSubagent            ThreadSource = "subagent"
	ThreadSourceMemoryConsolidation ThreadSource = "memory_consolidation"
)

type ThreadStartSource string

const (
	ThreadStartSourceStartup ThreadStartSource = "startup"
	ThreadStartSourceClear   ThreadStartSource = "clear"
)

type ThreadStartedNotification struct {
	Thread Thread `json:"thread"`
}

type ThreadStatusChangedNotification struct {
	Status   ThreadStatus `json:"status"`
	ThreadId string       `json:"threadId"`
}

type ThreadUnarchiveParams struct {
	ThreadId string `json:"threadId"`
}

type ThreadUnarchivedNotification struct {
	ThreadId string `json:"threadId"`
}

type ThreadUnsubscribeParams struct {
	ThreadId string `json:"threadId"`
}

type ThreadUnsubscribeResponse struct {
	Status ThreadUnsubscribeStatus `json:"status"`
}

type ThreadUnsubscribeStatus string

const (
	ThreadUnsubscribeStatusNotLoaded     ThreadUnsubscribeStatus = "notLoaded"
	ThreadUnsubscribeStatusNotSubscribed ThreadUnsubscribeStatus = "notSubscribed"
	ThreadUnsubscribeStatusUnsubscribed  ThreadUnsubscribeStatus = "unsubscribed"
)

type TokenUsageBreakdown struct {
	CachedInputTokens     int64 `json:"cachedInputTokens"`
	InputTokens           int64 `json:"inputTokens"`
	OutputTokens          int64 `json:"outputTokens"`
	ReasoningOutputTokens int64 `json:"reasoningOutputTokens"`
	TotalTokens           int64 `json:"totalTokens"`
}

type Tool struct {
	Meta         map[string]any   `json:"_meta,omitempty"`
	Annotations  map[string]any   `json:"annotations,omitempty"`
	Description  *string          `json:"description,omitempty"`
	Icons        []map[string]any `json:"icons,omitempty"`
	InputSchema  map[string]any   `json:"inputSchema"`
	Name         string           `json:"name"`
	OutputSchema map[string]any   `json:"outputSchema,omitempty"`
	Title        *string          `json:"title,omitempty"`
}

type ToolsV2 struct {
	ViewImage *bool                `json:"view_image,omitempty"`
	WebSearch *WebSearchToolConfig `json:"web_search,omitempty"`
}

type TurnDiffUpdatedNotification struct {
	Diff     string `json:"diff"`
	ThreadId string `json:"threadId"`
	TurnId   string `json:"turnId"`
}

type TurnEnvironmentParams struct {
	Cwd           AbsolutePathBuf `json:"cwd"`
	EnvironmentId string          `json:"environmentId"`
}

type TurnInterruptParams struct {
	ThreadId string `json:"threadId"`
	TurnId   string `json:"turnId"`
}

type TurnItemsView = json.RawMessage

type TurnPlanStep struct {
	Status TurnPlanStepStatus `json:"status"`
	Step   string             `json:"step"`
}

type TurnPlanStepStatus string

const (
	TurnPlanStepStatusPending    TurnPlanStepStatus = "pending"
	TurnPlanStepStatusInProgress TurnPlanStepStatus = "inProgress"
	TurnPlanStepStatusCompleted  TurnPlanStepStatus = "completed"
)

type TurnPlanUpdatedNotification struct {
	Explanation *string        `json:"explanation,omitempty"`
	Plan        []TurnPlanStep `json:"plan"`
	ThreadId    string         `json:"threadId"`
	TurnId      string         `json:"turnId"`
}

type TurnStartedNotification struct {
	ThreadId string `json:"threadId"`
	Turn     Turn   `json:"turn"`
}

type TurnSteerParams struct {
	ExpectedTurnId string      `json:"expectedTurnId"`
	Input          []UserInput `json:"input"`
	ThreadId       string      `json:"threadId"`
}

type Verbosity string

const (
	VerbosityLow    Verbosity = "low"
	VerbosityMedium Verbosity = "medium"
	VerbosityHigh   Verbosity = "high"
)

type WarningNotification struct {
	Message  string  `json:"message"`
	ThreadId *string `json:"threadId,omitempty"`
}

type WebSearchAction = json.RawMessage

type WebSearchContextSize string

const (
	WebSearchContextSizeLow    WebSearchContextSize = "low"
	WebSearchContextSizeMedium WebSearchContextSize = "medium"
	WebSearchContextSizeHigh   WebSearchContextSize = "high"
)

type WebSearchLocation struct {
	City     *string `json:"city,omitempty"`
	Country  *string `json:"country,omitempty"`
	Region   *string `json:"region,omitempty"`
	Timezone *string `json:"timezone,omitempty"`
}

type WebSearchMode string

const (
	WebSearchModeDisabled WebSearchMode = "disabled"
	WebSearchModeCached   WebSearchMode = "cached"
	WebSearchModeLive     WebSearchMode = "live"
)

type WebSearchToolConfig struct {
	AllowedDomains []string              `json:"allowed_domains,omitempty"`
	ContextSize    *WebSearchContextSize `json:"context_size,omitempty"`
	Location       *WebSearchLocation    `json:"location,omitempty"`
}

type WindowsSandboxReadiness string

const (
	WindowsSandboxReadinessReady          WindowsSandboxReadiness = "ready"
	WindowsSandboxReadinessNotConfigured  WindowsSandboxReadiness = "notConfigured"
	WindowsSandboxReadinessUpdateRequired WindowsSandboxReadiness = "updateRequired"
)

type WindowsSandboxReadinessResponse struct {
	Status WindowsSandboxReadiness `json:"status"`
}

type WindowsSandboxSetupCompletedNotification struct {
	Error   *string                 `json:"error,omitempty"`
	Mode    WindowsSandboxSetupMode `json:"mode"`
	Success bool                    `json:"success"`
}

type WindowsSandboxSetupMode string

const (
	WindowsSandboxSetupModeElevated   WindowsSandboxSetupMode = "elevated"
	WindowsSandboxSetupModeUnelevated WindowsSandboxSetupMode = "unelevated"
)

type WindowsSandboxSetupStartParams struct {
	Cwd  *AbsolutePathBuf        `json:"cwd,omitempty"`
	Mode WindowsSandboxSetupMode `json:"mode"`
}

type WindowsSandboxSetupStartResponse struct {
	Started bool `json:"started"`
}

type WindowsWorldWritableWarningNotification struct {
	ExtraCount  int64    `json:"extraCount"`
	FailedScan  bool     `json:"failedScan"`
	SamplePaths []string `json:"samplePaths"`
}

type WriteStatus string

const (
	WriteStatusOk           WriteStatus = "ok"
	WriteStatusOkOverridden WriteStatus = "okOverridden"
)
